#!/usr/bin/env python3
"""Text transforms used by the Windows firmware build (firmware/build.bat).

firmware/build.sh performs these steps with perl and sed.  cmd.exe has no usable
regular-expression tool, so build.bat delegates them to this helper instead.  The
transforms are kept deliberately identical to the perl one-liners in build.sh:

  version        Parse FIRMWARE_VERSION from firmware_build.h and pack it as 0x00MMmmpp.
  linker-cmd     Point the XDC-generated linker.cmd at this machine's tools, then rebase it
                 to 0x8000 and substitute the locally built configuration object and SYS/BIOS
                 library.
  compiler-opt   Point the XDC-generated compiler.opt include paths at this machine.
  config-source  Rename the generated ResetISR so boot_nonrom_startup.c can provide its own.

The XDC configPkg was generated by CCS on one developer machine and records that machine's
absolute SDK, XDCtools, compiler and workspace paths.  ``relocate_paths`` rewrites every such
path to the location supplied on the command line, so the checked-in configPkg builds anywhere.
Generated files always use forward slashes, which the TI tools accept on every host, and are
written in the Windows ANSI code page on Windows because that is what armcl reads.

Runs on Python 3.6 or newer.
"""
import argparse
import locale
import os
import re
import sys
from pathlib import Path

CGT_DIRECTORY = "ti-cgt-arm_18.12.5.LTS"
SDK_DIRECTORY = "simplelink_cc13x0_sdk_4_20_02_07"
XDCTOOLS_DIRECTORY = "xdctools_3_51_03_28_core"
CONFIG_DIRECTORY = "configPkg_nonrom5"

APP_BASE = 0x8000
VERSION_LIMIT = 255

VERSION_DEFINE = re.compile(
    r'^[ \t]*#define[ \t]+FIRMWARE_VERSION[ \t]+"([0-9]+\.[0-9]+\.[0-9]+)"[ \t]*$', re.MULTILINE)
SEMVER = re.compile(r"^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$")

# A double-quoted token; a backslash escapes the next character, so the escaped quotes in
# -Dxdc_cfg__xheader__="\"...\"" keep the whole define inside one token.
QUOTED_TOKEN = re.compile(r'"(?:\\.|[^"\\\n])*"')


def output_encoding():
    """Encoding of generated command files: the ANSI code page on Windows, UTF-8 elsewhere.

    armcl reads its command files in the system ANSI code page whatever Python's own I/O
    encoding is, so Python's UTF-8 mode (PYTHONUTF8=1, the default from Python 3.15) must not
    leak into these files: ``locale.getencoding`` (3.11+) ignores UTF-8 mode and the ``mbcs``
    codec always means the ANSI code page.
    """
    if os.name == "nt":
        get_encoding = getattr(locale, "getencoding", None)
        return get_encoding() if get_encoding else "mbcs"
    return "utf-8"


def to_posix(path):
    """Return ``path`` with forward slashes and no trailing slash (TI command-file form)."""
    text = str(path).replace("\\", "/")
    while len(text) > 1 and text.endswith("/") and not text.endswith(":/"):
        text = text[:-1]
    return text


def read_text(path, lenient=False):
    """Read ``path`` without translating line endings so they can be preserved on write.

    Files are UTF-8 (the CCS-generated inputs are ASCII).  A file saved in the local ANSI
    code page is decoded with that code page instead; with ``lenient`` undecodable bytes are
    replaced, which is acceptable for a header whose only relevant line is ASCII.
    """
    data = Path(path).read_bytes()
    try:
        return data.decode("utf-8")
    except UnicodeDecodeError:
        fallback = output_encoding() if os.name == "nt" else (locale.getpreferredencoding(False) or "latin-1")
        return data.decode(fallback, "replace" if lenient else "strict")


def write_text(path, text):
    """Write ``text`` verbatim (no newline translation) in the encoding the TI tools read."""
    encoding = output_encoding()
    try:
        data = text.encode(encoding)
    except UnicodeEncodeError as error:
        raise ValueError("a path cannot be represented in the %s code page that the TI tools "
                         "read; use an ASCII installation path (%s)" % (encoding, error))
    Path(path).write_bytes(data)


def detect_newline(text):
    return "\r\n" if "\r\n" in text else "\n"


def parse_version(header_text):
    """Return (version_string, packed_code) for the FIRMWARE_VERSION define.

    Mirrors the sed/bash validation in firmware/build.sh: exactly one SemVer
    ``major.minor.patch`` string with no leading zeros and every component <= 255.
    """
    matches = VERSION_DEFINE.findall(header_text.replace("\r\n", "\n"))
    if len(matches) != 1:
        raise ValueError("FIRMWARE_VERSION must be a SemVer string (major.minor.patch)")
    version = matches[0]
    parts = SEMVER.match(version)
    if not parts:
        raise ValueError("FIRMWARE_VERSION must be a SemVer string (major.minor.patch)")
    major, minor, patch = (int(part) for part in parts.groups())
    if max(major, minor, patch) > VERSION_LIMIT:
        raise ValueError("FIRMWARE_VERSION components must not exceed %u: %s"
                         % (VERSION_LIMIT, version))
    return version, (major << 16) | (minor << 8) | patch


def _relocate(text, directory, root):
    """Replace every absolute path ending in ``directory`` with ``root``.

    A path is POSIX ("/...") or Windows ("C:/..."), ends with the well-known directory name
    and is followed by a separator, quote, whitespace, ';' or the end of the text.  The text
    is processed token by token: inside a double-quoted token a path may contain spaces, so
    the match starts at the first path character after the quote; outside quotes a path
    cannot contain whitespace, so it is a whole token.  Either way a match can never start in
    the middle of a path, which is what makes the rewrite safe to apply more than once and
    safe for roots that contain spaces.
    """
    name = re.escape(directory)
    in_quotes = re.compile(r'(?:[A-Za-z]:)?/[^"\n;]*?/' + name + r'(?=[/\\"\s;]|$)')
    bare = re.compile(r'(?:[A-Za-z]:)?/[^"\s;]*?/' + name + r'(?=[/\\"\s;]|$)')
    pieces = QUOTED_TOKEN.split(text)
    tokens = QUOTED_TOKEN.findall(text)
    output = []
    for index, piece in enumerate(pieces):
        output.append(bare.sub(lambda match: root, piece))
        if index < len(tokens):
            output.append(in_quotes.sub(lambda match: root, tokens[index]))
    return "".join(output)


def relocate_paths(text, sdk, xdctools, cgt, cfg):
    """Rewrite the generating machine's SDK/XDCtools/compiler/configPkg paths to local ones."""
    sdk, xdctools, cgt, cfg = (to_posix(root) for root in (sdk, xdctools, cgt, cfg))
    text = _relocate(text, SDK_DIRECTORY, sdk)
    text = _relocate(text, XDCTOOLS_DIRECTORY, xdctools)
    text = _relocate(text, CGT_DIRECTORY, cgt)
    text = _relocate(text, CONFIG_DIRECTORY, cfg)
    # compiler.opt carries the compiler include directory unquoted; quote it so an
    # installation under a directory with spaces still works.
    unquoted_include = re.compile(r'(?<!")-I' + re.escape(cgt) + r'/include(?=\s|$)',
                                  re.MULTILINE)
    return unquoted_include.sub(lambda match: '-I"%s/include"' % cgt, text)


def rebase_linker_cmd(text, boot_config_object, boot_config_sysbios):
    """Apply the perl edits from firmware/build.sh to the generated linker.cmd."""
    # 16-bit flash addresses move up by the bootloader size; the reset vectors land at 0x8000.
    text = re.sub(r"0x0000([0-9A-Fa-f]{4})",
                  lambda match: "0x%08X" % (int(match.group(0), 16) + APP_BASE), text)
    text = re.sub(r"(\.resetVecs: load > )0x[0-9A-Fa-f]+",
                  lambda match: match.group(1) + "0x%08X" % APP_BASE, text)
    text = text.replace("/rfPacketRx/", "/firmware/")
    # The generated configuration object and SYS/BIOS library are rebuilt locally.
    text = re.sub(r'-l"[^"]*/(?:boot_)?release_pem3\.oem3"',
                  lambda match: '-l"%s"' % to_posix(boot_config_object), text, count=1)
    text = re.sub(r'-l"[^"]*/boot_release_pem3\.src/sysbios/sysbios\.aem3"',
                  lambda match: '-l"%s"' % to_posix(boot_config_sysbios), text, count=1)
    return text


def build_linker_cmd(text, sdk, xdctools, cgt, cfg, boot_config_object, boot_config_sysbios):
    """Produce the application linker command file from the generated one.

    Relocation runs first so that the local paths inserted by ``rebase_linker_cmd`` are never
    fed back through the relocation patterns.
    """
    text = relocate_paths(text, sdk, xdctools, cgt, cfg)
    return rebase_linker_cmd(text, boot_config_object, boot_config_sysbios)


def patch_config_source(text):
    """Rename the generated reset entry so the application provides ResetISR itself."""
    newline = detect_newline(text)
    text = re.sub(r"extern Void _c_int00\(\);",
                  lambda match: "extern Void ResetISR();" + newline + "extern Void _c_int00();",
                  text)
    text = re.sub(r"\(UInt32\)\(&_c_int00\),", lambda match: "(UInt32)(&ResetISR),", text)
    text = re.sub(r"Void ResetISR \(\)", lambda match: "Void generatedResetISR ()", text)
    return text


def _add_relocation_arguments(parser):
    parser.add_argument("--sdk", required=True, help="SimpleLink CC13x0 SDK root")
    parser.add_argument("--xdctools", required=True, help="XDCtools core root")
    parser.add_argument("--cgt", required=True, help="TI ARM CGT root")
    parser.add_argument("--cfg", required=True, help="configPkg_nonrom5 directory")


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    commands = parser.add_subparsers(dest="command")
    commands.required = True

    version = commands.add_parser("version", help="print 'major.minor.patch code 0xcode'")
    version.add_argument("header", type=Path)

    linker = commands.add_parser("linker-cmd", help="write the rebased linker command file")
    linker.add_argument("--input", required=True, type=Path)
    linker.add_argument("--output", required=True, type=Path)
    linker.add_argument("--boot-config-object", required=True)
    linker.add_argument("--boot-config-sysbios", required=True)
    _add_relocation_arguments(linker)

    compiler = commands.add_parser("compiler-opt", help="write the relocated compiler options")
    compiler.add_argument("--input", required=True, type=Path)
    compiler.add_argument("--output", required=True, type=Path)
    _add_relocation_arguments(compiler)

    config = commands.add_parser("config-source", help="write the patched configuration source")
    config.add_argument("--input", required=True, type=Path)
    config.add_argument("--output", required=True, type=Path)

    args = parser.parse_args(argv)
    subject = args.header if args.command == "version" else args.input
    try:
        if args.command == "version":
            version_string, code = parse_version(read_text(args.header, lenient=True))
            print("%s %u 0x%08X" % (version_string, code, code))
        elif args.command == "linker-cmd":
            write_text(args.output, build_linker_cmd(
                read_text(args.input), args.sdk, args.xdctools, args.cgt, args.cfg,
                args.boot_config_object, args.boot_config_sysbios))
        elif args.command == "compiler-opt":
            write_text(args.output, relocate_paths(read_text(args.input), args.sdk,
                                                   args.xdctools, args.cgt, args.cfg))
        elif args.command == "config-source":
            write_text(args.output, patch_config_source(read_text(args.input)))
    except (OSError, ValueError) as error:
        print("%s: %s: %s" % (parser.prog, error, subject), file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
